# Generated by Django 4.2.6 on 2023-12-11 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_emp_dept_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('losal', models.IntegerField()),
                ('hisal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_sal', models.IntegerField()),
                ('emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.emp')),
            ],
        ),
    ]
